### ISSUE TITLE
Update to 1.2

### ISSUE THREAD

**Issue by Recydywa** [kenvandine/widelands#1]
There was a new release of Widelands.

The 1.2 version is in the PPA since 30th March. I checked this snapcraft.yaml and build version 1.2 of the package on my install and it works.

**Comment by kenvandine** [comment]
1.2 is no in the edge channel, after testing I'll get it promoted to stable.

Thanks so much for flagging this!

**Comment by Recydywa** [comment]
Thank you for quick response.

I installed the edge channel version and the game starts and has sound. I didn't test anything else yet, maybe tomorrow.

**Comment by Recydywa** [comment]
The snap version doesn't connect with the add-ons server.  The error message is unable to create socket.

I don't know if that was also a problem with previous version, but I suspect that it was.

The install from Widelands PPA doesn't have such problem.

**Comment by Recydywa** [comment]
The 1.1 version of snap also cannot connect to add-ons server.

**Comment by kenvandine** [comment]
ok, so not a regression.  Could you please file a separate issue for the add-ons server?  I think it just needs another plug added in the snap, but will need to debug it.

**Comment by Recydywa** [comment]
I filed the issue.

I also thought that it just needs another plug.

**Comment by kenvandine** [comment]
1.2 is now released to stable
