### ISSUE TITLE
Cannot connect to add-ons server

### ISSUE THREAD

**Issue by Recydywa** [kenvandine/widelands#2]
The snap package cannot connect to add-ons server.

In the add-ons menu of Widelands I press the refresh button to get the list of add-ons, but this fails. This is screenshot of the problem.

![Zrzut ekranu z 2024-05-03 17-18-22](https://github.com/kenvandine/widelands/assets/7874141/add05aa9-60c0-4aeb-881b-0821d06bde98)

**Comment by kenvandine** [comment]
This is now published in the edge channel, help testing it would be appreciated.

**Comment by Recydywa** [comment]
It works.

Add-on manager connected to the server and got the list of add-ons. I also installed one map.

**Comment by kenvandine** [comment]
This is now in stable, thanks!
